### ISSUE TITLE
tufte-handout class?

### ISSUE THREAD

**Issue by bbolker** [fredguth/tufte-quarto#1]
Can this extension handle a standalone handout, in the style of the [rmarkdown tufte style](https://rstudio.github.io/tufte/)? Or, do you know if anyone has already done this/is working on it?  (I will experiment for myself when I get a chance, but if this is a quick/easy answer for you ...) ?

**Comment by fredguth** [comment]
You can add to your `_quarto.yml`:

````
project:
    type: tufte
book:
  open-graph: true

...

format:
  pdf:
    documentclass: tufte-handout
bibliography: references.bib

````

But  notice the project structure was done thinking about a book with a companion site.  Thus, you probably will won't need many files/folders.
